[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.7.6"
evm_version = "istanbul"

# 允许多版本 Solidity 编译
auto_detect_solc = true
ignored_error_codes = [1878, 5574]

# Optimizer settings - 匹配 Uniswap V3 原始设置
via_ir = false
optimizer = true
optimizer_runs = 1000000

# 测试配置
[profile.default.fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
