[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200

[profile.default.fuzz]
runs = 256

[fmt]
line_length = 100
tab_width = 4
