[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Compiler settings
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"
auto_detect_solc = false
bytecode_hash = "none"
cbor_metadata = false


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
